// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParticipantMessage.proto

package com.photon.photonchain.network.proto;

public final class ParticipantMessage {
  private ParticipantMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParticipantOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Participant)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string participant = 1;</code>
     */
    boolean hasParticipant();
    /**
     * <code>required string participant = 1;</code>
     */
    java.lang.String getParticipant();
    /**
     * <code>required string participant = 1;</code>
     */
    com.google.protobuf.ByteString
        getParticipantBytes();

    /**
     * <code>required int32 count = 2;</code>
     */
    boolean hasCount();
    /**
     * <code>required int32 count = 2;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code Participant}
   */
  public  static final class Participant extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Participant)
      ParticipantOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Participant.newBuilder() to construct.
    private Participant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Participant() {
      participant_ = "";
      count_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Participant(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              participant_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.photon.photonchain.network.proto.ParticipantMessage.internal_static_Participant_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.photon.photonchain.network.proto.ParticipantMessage.internal_static_Participant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.photon.photonchain.network.proto.ParticipantMessage.Participant.class, com.photon.photonchain.network.proto.ParticipantMessage.Participant.Builder.class);
    }

    private int bitField0_;
    public static final int PARTICIPANT_FIELD_NUMBER = 1;
    private volatile java.lang.Object participant_;
    /**
     * <code>required string participant = 1;</code>
     */
    public boolean hasParticipant() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string participant = 1;</code>
     */
    public java.lang.String getParticipant() {
      java.lang.Object ref = participant_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          participant_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string participant = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParticipantBytes() {
      java.lang.Object ref = participant_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>required int32 count = 2;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasParticipant()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, participant_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, participant_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.photon.photonchain.network.proto.ParticipantMessage.Participant)) {
        return super.equals(obj);
      }
      com.photon.photonchain.network.proto.ParticipantMessage.Participant other = (com.photon.photonchain.network.proto.ParticipantMessage.Participant) obj;

      boolean result = true;
      result = result && (hasParticipant() == other.hasParticipant());
      if (hasParticipant()) {
        result = result && getParticipant()
            .equals(other.getParticipant());
      }
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParticipant()) {
        hash = (37 * hash) + PARTICIPANT_FIELD_NUMBER;
        hash = (53 * hash) + getParticipant().hashCode();
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getCount();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.photon.photonchain.network.proto.ParticipantMessage.Participant prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Participant}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Participant)
        com.photon.photonchain.network.proto.ParticipantMessage.ParticipantOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.photon.photonchain.network.proto.ParticipantMessage.internal_static_Participant_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.photon.photonchain.network.proto.ParticipantMessage.internal_static_Participant_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.photon.photonchain.network.proto.ParticipantMessage.Participant.class, com.photon.photonchain.network.proto.ParticipantMessage.Participant.Builder.class);
      }

      // Construct using com.photon.photonchain.network.proto.ParticipantMessage.Participant.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        participant_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.photon.photonchain.network.proto.ParticipantMessage.internal_static_Participant_descriptor;
      }

      public com.photon.photonchain.network.proto.ParticipantMessage.Participant getDefaultInstanceForType() {
        return com.photon.photonchain.network.proto.ParticipantMessage.Participant.getDefaultInstance();
      }

      public com.photon.photonchain.network.proto.ParticipantMessage.Participant build() {
        com.photon.photonchain.network.proto.ParticipantMessage.Participant result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.photon.photonchain.network.proto.ParticipantMessage.Participant buildPartial() {
        com.photon.photonchain.network.proto.ParticipantMessage.Participant result = new com.photon.photonchain.network.proto.ParticipantMessage.Participant(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.participant_ = participant_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.photon.photonchain.network.proto.ParticipantMessage.Participant) {
          return mergeFrom((com.photon.photonchain.network.proto.ParticipantMessage.Participant)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.photon.photonchain.network.proto.ParticipantMessage.Participant other) {
        if (other == com.photon.photonchain.network.proto.ParticipantMessage.Participant.getDefaultInstance()) return this;
        if (other.hasParticipant()) {
          bitField0_ |= 0x00000001;
          participant_ = other.participant_;
          onChanged();
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasParticipant()) {
          return false;
        }
        if (!hasCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.photon.photonchain.network.proto.ParticipantMessage.Participant parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.photon.photonchain.network.proto.ParticipantMessage.Participant) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object participant_ = "";
      /**
       * <code>required string participant = 1;</code>
       */
      public boolean hasParticipant() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string participant = 1;</code>
       */
      public java.lang.String getParticipant() {
        java.lang.Object ref = participant_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            participant_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string participant = 1;</code>
       */
      public com.google.protobuf.ByteString
          getParticipantBytes() {
        java.lang.Object ref = participant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          participant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string participant = 1;</code>
       */
      public Builder setParticipant(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        participant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string participant = 1;</code>
       */
      public Builder clearParticipant() {
        bitField0_ = (bitField0_ & ~0x00000001);
        participant_ = getDefaultInstance().getParticipant();
        onChanged();
        return this;
      }
      /**
       * <code>required string participant = 1;</code>
       */
      public Builder setParticipantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        participant_ = value;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>required int32 count = 2;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Participant)
    }

    // @@protoc_insertion_point(class_scope:Participant)
    private static final com.photon.photonchain.network.proto.ParticipantMessage.Participant DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.photon.photonchain.network.proto.ParticipantMessage.Participant();
    }

    public static com.photon.photonchain.network.proto.ParticipantMessage.Participant getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Participant>
        PARSER = new com.google.protobuf.AbstractParser<Participant>() {
      public Participant parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Participant(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Participant> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Participant> getParserForType() {
      return PARSER;
    }

    public com.photon.photonchain.network.proto.ParticipantMessage.Participant getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Participant_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Participant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ParticipantMessage.proto\"1\n\013Participan" +
      "t\022\023\n\013participant\030\001 \002(\t\022\r\n\005count\030\002 \002(\005B:\n" +
      "$com.photon.photonchain.network.protoB\022P" +
      "articipantMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Participant_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Participant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Participant_descriptor,
        new java.lang.String[] { "Participant", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
