// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionMessage.proto

package com.photon.photonchain.network.proto;

public final class TransactionMessage {
  private TransactionMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 blockHeight = 1;</code>
     */
    boolean hasBlockHeight();
    /**
     * <code>required int64 blockHeight = 1;</code>
     */
    long getBlockHeight();

    /**
     * <code>required int64 lockTime = 2;</code>
     */
    boolean hasLockTime();
    /**
     * <code>required int64 lockTime = 2;</code>
     */
    long getLockTime();

    /**
     * <code>required bytes transSignature = 3;</code>
     */
    boolean hasTransSignature();
    /**
     * <code>required bytes transSignature = 3;</code>
     */
    com.google.protobuf.ByteString getTransSignature();

    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    boolean hasTransactionHead();
    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getTransactionHead();
    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder getTransactionHeadOrBuilder();

    /**
     * <code>required string transFrom = 5;</code>
     */
    boolean hasTransFrom();
    /**
     * <code>required string transFrom = 5;</code>
     */
    java.lang.String getTransFrom();
    /**
     * <code>required string transFrom = 5;</code>
     */
    com.google.protobuf.ByteString
        getTransFromBytes();

    /**
     * <code>required string transTo = 6;</code>
     */
    boolean hasTransTo();
    /**
     * <code>required string transTo = 6;</code>
     */
    java.lang.String getTransTo();
    /**
     * <code>required string transTo = 6;</code>
     */
    com.google.protobuf.ByteString
        getTransToBytes();

    /**
     * <code>optional string remark = 7;</code>
     */
    boolean hasRemark();
    /**
     * <code>optional string remark = 7;</code>
     */
    java.lang.String getRemark();
    /**
     * <code>optional string remark = 7;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>required string tokenName = 8;</code>
     */
    boolean hasTokenName();
    /**
     * <code>required string tokenName = 8;</code>
     */
    java.lang.String getTokenName();
    /**
     * <code>required string tokenName = 8;</code>
     */
    com.google.protobuf.ByteString
        getTokenNameBytes();

    /**
     * <code>required int32 transType = 9;</code>
     */
    boolean hasTransType();
    /**
     * <code>required int32 transType = 9;</code>
     */
    int getTransType();
  }
  /**
   * Protobuf type {@code Transaction}
   */
  public  static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      blockHeight_ = 0L;
      lockTime_ = 0L;
      transSignature_ = com.google.protobuf.ByteString.EMPTY;
      transFrom_ = "";
      transTo_ = "";
      remark_ = "";
      tokenName_ = "";
      transType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              blockHeight_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lockTime_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              transSignature_ = input.readBytes();
              break;
            }
            case 34: {
              com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = transactionHead_.toBuilder();
              }
              transactionHead_ = input.readMessage(com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactionHead_);
                transactionHead_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              transFrom_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              transTo_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              remark_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              tokenName_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              transType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.photon.photonchain.network.proto.TransactionMessage.internal_static_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.photon.photonchain.network.proto.TransactionMessage.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.photon.photonchain.network.proto.TransactionMessage.Transaction.class, com.photon.photonchain.network.proto.TransactionMessage.Transaction.Builder.class);
    }

    private int bitField0_;
    public static final int BLOCKHEIGHT_FIELD_NUMBER = 1;
    private long blockHeight_;
    /**
     * <code>required int64 blockHeight = 1;</code>
     */
    public boolean hasBlockHeight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 blockHeight = 1;</code>
     */
    public long getBlockHeight() {
      return blockHeight_;
    }

    public static final int LOCKTIME_FIELD_NUMBER = 2;
    private long lockTime_;
    /**
     * <code>required int64 lockTime = 2;</code>
     */
    public boolean hasLockTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 lockTime = 2;</code>
     */
    public long getLockTime() {
      return lockTime_;
    }

    public static final int TRANSSIGNATURE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString transSignature_;
    /**
     * <code>required bytes transSignature = 3;</code>
     */
    public boolean hasTransSignature() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes transSignature = 3;</code>
     */
    public com.google.protobuf.ByteString getTransSignature() {
      return transSignature_;
    }

    public static final int TRANSACTIONHEAD_FIELD_NUMBER = 4;
    private com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead transactionHead_;
    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    public boolean hasTransactionHead() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getTransactionHead() {
      return transactionHead_ == null ? com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance() : transactionHead_;
    }
    /**
     * <code>required .TransactionHead transactionHead = 4;</code>
     */
    public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder getTransactionHeadOrBuilder() {
      return transactionHead_ == null ? com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance() : transactionHead_;
    }

    public static final int TRANSFROM_FIELD_NUMBER = 5;
    private volatile java.lang.Object transFrom_;
    /**
     * <code>required string transFrom = 5;</code>
     */
    public boolean hasTransFrom() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string transFrom = 5;</code>
     */
    public java.lang.String getTransFrom() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transFrom = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTransFromBytes() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSTO_FIELD_NUMBER = 6;
    private volatile java.lang.Object transTo_;
    /**
     * <code>required string transTo = 6;</code>
     */
    public boolean hasTransTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string transTo = 6;</code>
     */
    public java.lang.String getTransTo() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transTo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTransToBytes() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 7;
    private volatile java.lang.Object remark_;
    /**
     * <code>optional string remark = 7;</code>
     */
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string remark = 7;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remark_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string remark = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object tokenName_;
    /**
     * <code>required string tokenName = 8;</code>
     */
    public boolean hasTokenName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string tokenName = 8;</code>
     */
    public java.lang.String getTokenName() {
      java.lang.Object ref = tokenName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tokenName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTokenNameBytes() {
      java.lang.Object ref = tokenName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSTYPE_FIELD_NUMBER = 9;
    private int transType_;
    /**
     * <code>required int32 transType = 9;</code>
     */
    public boolean hasTransType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 transType = 9;</code>
     */
    public int getTransType() {
      return transType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBlockHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLockTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransactionHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTokenName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTransactionHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, blockHeight_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, lockTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, transSignature_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getTransactionHead());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, transFrom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, transTo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, remark_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tokenName_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, transType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, blockHeight_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lockTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, transSignature_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTransactionHead());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, transFrom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, transTo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, remark_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tokenName_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, transType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.photon.photonchain.network.proto.TransactionMessage.Transaction)) {
        return super.equals(obj);
      }
      com.photon.photonchain.network.proto.TransactionMessage.Transaction other = (com.photon.photonchain.network.proto.TransactionMessage.Transaction) obj;

      boolean result = true;
      result = result && (hasBlockHeight() == other.hasBlockHeight());
      if (hasBlockHeight()) {
        result = result && (getBlockHeight()
            == other.getBlockHeight());
      }
      result = result && (hasLockTime() == other.hasLockTime());
      if (hasLockTime()) {
        result = result && (getLockTime()
            == other.getLockTime());
      }
      result = result && (hasTransSignature() == other.hasTransSignature());
      if (hasTransSignature()) {
        result = result && getTransSignature()
            .equals(other.getTransSignature());
      }
      result = result && (hasTransactionHead() == other.hasTransactionHead());
      if (hasTransactionHead()) {
        result = result && getTransactionHead()
            .equals(other.getTransactionHead());
      }
      result = result && (hasTransFrom() == other.hasTransFrom());
      if (hasTransFrom()) {
        result = result && getTransFrom()
            .equals(other.getTransFrom());
      }
      result = result && (hasTransTo() == other.hasTransTo());
      if (hasTransTo()) {
        result = result && getTransTo()
            .equals(other.getTransTo());
      }
      result = result && (hasRemark() == other.hasRemark());
      if (hasRemark()) {
        result = result && getRemark()
            .equals(other.getRemark());
      }
      result = result && (hasTokenName() == other.hasTokenName());
      if (hasTokenName()) {
        result = result && getTokenName()
            .equals(other.getTokenName());
      }
      result = result && (hasTransType() == other.hasTransType());
      if (hasTransType()) {
        result = result && (getTransType()
            == other.getTransType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBlockHeight()) {
        hash = (37 * hash) + BLOCKHEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBlockHeight());
      }
      if (hasLockTime()) {
        hash = (37 * hash) + LOCKTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLockTime());
      }
      if (hasTransSignature()) {
        hash = (37 * hash) + TRANSSIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getTransSignature().hashCode();
      }
      if (hasTransactionHead()) {
        hash = (37 * hash) + TRANSACTIONHEAD_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionHead().hashCode();
      }
      if (hasTransFrom()) {
        hash = (37 * hash) + TRANSFROM_FIELD_NUMBER;
        hash = (53 * hash) + getTransFrom().hashCode();
      }
      if (hasTransTo()) {
        hash = (37 * hash) + TRANSTO_FIELD_NUMBER;
        hash = (53 * hash) + getTransTo().hashCode();
      }
      if (hasRemark()) {
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemark().hashCode();
      }
      if (hasTokenName()) {
        hash = (37 * hash) + TOKENNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTokenName().hashCode();
      }
      if (hasTransType()) {
        hash = (37 * hash) + TRANSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTransType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.photon.photonchain.network.proto.TransactionMessage.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        com.photon.photonchain.network.proto.TransactionMessage.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.photon.photonchain.network.proto.TransactionMessage.internal_static_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.photon.photonchain.network.proto.TransactionMessage.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.photon.photonchain.network.proto.TransactionMessage.Transaction.class, com.photon.photonchain.network.proto.TransactionMessage.Transaction.Builder.class);
      }

      // Construct using com.photon.photonchain.network.proto.TransactionMessage.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionHeadFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        blockHeight_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        lockTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        transSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (transactionHeadBuilder_ == null) {
          transactionHead_ = null;
        } else {
          transactionHeadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        transFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        transTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        tokenName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        transType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.photon.photonchain.network.proto.TransactionMessage.internal_static_Transaction_descriptor;
      }

      public com.photon.photonchain.network.proto.TransactionMessage.Transaction getDefaultInstanceForType() {
        return com.photon.photonchain.network.proto.TransactionMessage.Transaction.getDefaultInstance();
      }

      public com.photon.photonchain.network.proto.TransactionMessage.Transaction build() {
        com.photon.photonchain.network.proto.TransactionMessage.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.photon.photonchain.network.proto.TransactionMessage.Transaction buildPartial() {
        com.photon.photonchain.network.proto.TransactionMessage.Transaction result = new com.photon.photonchain.network.proto.TransactionMessage.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.blockHeight_ = blockHeight_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lockTime_ = lockTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.transSignature_ = transSignature_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (transactionHeadBuilder_ == null) {
          result.transactionHead_ = transactionHead_;
        } else {
          result.transactionHead_ = transactionHeadBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.transFrom_ = transFrom_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.transTo_ = transTo_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.remark_ = remark_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.tokenName_ = tokenName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.transType_ = transType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.photon.photonchain.network.proto.TransactionMessage.Transaction) {
          return mergeFrom((com.photon.photonchain.network.proto.TransactionMessage.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.photon.photonchain.network.proto.TransactionMessage.Transaction other) {
        if (other == com.photon.photonchain.network.proto.TransactionMessage.Transaction.getDefaultInstance()) return this;
        if (other.hasBlockHeight()) {
          setBlockHeight(other.getBlockHeight());
        }
        if (other.hasLockTime()) {
          setLockTime(other.getLockTime());
        }
        if (other.hasTransSignature()) {
          setTransSignature(other.getTransSignature());
        }
        if (other.hasTransactionHead()) {
          mergeTransactionHead(other.getTransactionHead());
        }
        if (other.hasTransFrom()) {
          bitField0_ |= 0x00000010;
          transFrom_ = other.transFrom_;
          onChanged();
        }
        if (other.hasTransTo()) {
          bitField0_ |= 0x00000020;
          transTo_ = other.transTo_;
          onChanged();
        }
        if (other.hasRemark()) {
          bitField0_ |= 0x00000040;
          remark_ = other.remark_;
          onChanged();
        }
        if (other.hasTokenName()) {
          bitField0_ |= 0x00000080;
          tokenName_ = other.tokenName_;
          onChanged();
        }
        if (other.hasTransType()) {
          setTransType(other.getTransType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBlockHeight()) {
          return false;
        }
        if (!hasLockTime()) {
          return false;
        }
        if (!hasTransSignature()) {
          return false;
        }
        if (!hasTransactionHead()) {
          return false;
        }
        if (!hasTransFrom()) {
          return false;
        }
        if (!hasTransTo()) {
          return false;
        }
        if (!hasTokenName()) {
          return false;
        }
        if (!hasTransType()) {
          return false;
        }
        if (!getTransactionHead().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.photon.photonchain.network.proto.TransactionMessage.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.photon.photonchain.network.proto.TransactionMessage.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long blockHeight_ ;
      /**
       * <code>required int64 blockHeight = 1;</code>
       */
      public boolean hasBlockHeight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 blockHeight = 1;</code>
       */
      public long getBlockHeight() {
        return blockHeight_;
      }
      /**
       * <code>required int64 blockHeight = 1;</code>
       */
      public Builder setBlockHeight(long value) {
        bitField0_ |= 0x00000001;
        blockHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 blockHeight = 1;</code>
       */
      public Builder clearBlockHeight() {
        bitField0_ = (bitField0_ & ~0x00000001);
        blockHeight_ = 0L;
        onChanged();
        return this;
      }

      private long lockTime_ ;
      /**
       * <code>required int64 lockTime = 2;</code>
       */
      public boolean hasLockTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 lockTime = 2;</code>
       */
      public long getLockTime() {
        return lockTime_;
      }
      /**
       * <code>required int64 lockTime = 2;</code>
       */
      public Builder setLockTime(long value) {
        bitField0_ |= 0x00000002;
        lockTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 lockTime = 2;</code>
       */
      public Builder clearLockTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lockTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes transSignature = 3;</code>
       */
      public boolean hasTransSignature() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes transSignature = 3;</code>
       */
      public com.google.protobuf.ByteString getTransSignature() {
        return transSignature_;
      }
      /**
       * <code>required bytes transSignature = 3;</code>
       */
      public Builder setTransSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        transSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes transSignature = 3;</code>
       */
      public Builder clearTransSignature() {
        bitField0_ = (bitField0_ & ~0x00000004);
        transSignature_ = getDefaultInstance().getTransSignature();
        onChanged();
        return this;
      }

      private com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead transactionHead_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder> transactionHeadBuilder_;
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public boolean hasTransactionHead() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getTransactionHead() {
        if (transactionHeadBuilder_ == null) {
          return transactionHead_ == null ? com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance() : transactionHead_;
        } else {
          return transactionHeadBuilder_.getMessage();
        }
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public Builder setTransactionHead(com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead value) {
        if (transactionHeadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactionHead_ = value;
          onChanged();
        } else {
          transactionHeadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public Builder setTransactionHead(
          com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder builderForValue) {
        if (transactionHeadBuilder_ == null) {
          transactionHead_ = builderForValue.build();
          onChanged();
        } else {
          transactionHeadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public Builder mergeTransactionHead(com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead value) {
        if (transactionHeadBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              transactionHead_ != null &&
              transactionHead_ != com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance()) {
            transactionHead_ =
              com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.newBuilder(transactionHead_).mergeFrom(value).buildPartial();
          } else {
            transactionHead_ = value;
          }
          onChanged();
        } else {
          transactionHeadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public Builder clearTransactionHead() {
        if (transactionHeadBuilder_ == null) {
          transactionHead_ = null;
          onChanged();
        } else {
          transactionHeadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder getTransactionHeadBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTransactionHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder getTransactionHeadOrBuilder() {
        if (transactionHeadBuilder_ != null) {
          return transactionHeadBuilder_.getMessageOrBuilder();
        } else {
          return transactionHead_ == null ?
              com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance() : transactionHead_;
        }
      }
      /**
       * <code>required .TransactionHead transactionHead = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder> 
          getTransactionHeadFieldBuilder() {
        if (transactionHeadBuilder_ == null) {
          transactionHeadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder>(
                  getTransactionHead(),
                  getParentForChildren(),
                  isClean());
          transactionHead_ = null;
        }
        return transactionHeadBuilder_;
      }

      private java.lang.Object transFrom_ = "";
      /**
       * <code>required string transFrom = 5;</code>
       */
      public boolean hasTransFrom() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string transFrom = 5;</code>
       */
      public java.lang.String getTransFrom() {
        java.lang.Object ref = transFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transFrom = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTransFromBytes() {
        java.lang.Object ref = transFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transFrom = 5;</code>
       */
      public Builder setTransFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        transFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 5;</code>
       */
      public Builder clearTransFrom() {
        bitField0_ = (bitField0_ & ~0x00000010);
        transFrom_ = getDefaultInstance().getTransFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 5;</code>
       */
      public Builder setTransFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        transFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transTo_ = "";
      /**
       * <code>required string transTo = 6;</code>
       */
      public boolean hasTransTo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string transTo = 6;</code>
       */
      public java.lang.String getTransTo() {
        java.lang.Object ref = transTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transTo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTransToBytes() {
        java.lang.Object ref = transTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transTo = 6;</code>
       */
      public Builder setTransTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        transTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 6;</code>
       */
      public Builder clearTransTo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        transTo_ = getDefaultInstance().getTransTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 6;</code>
       */
      public Builder setTransToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        transTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>optional string remark = 7;</code>
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remark_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00000040);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        remark_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenName_ = "";
      /**
       * <code>required string tokenName = 8;</code>
       */
      public boolean hasTokenName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string tokenName = 8;</code>
       */
      public java.lang.String getTokenName() {
        java.lang.Object ref = tokenName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tokenName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tokenName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTokenNameBytes() {
        java.lang.Object ref = tokenName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tokenName = 8;</code>
       */
      public Builder setTokenName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        tokenName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tokenName = 8;</code>
       */
      public Builder clearTokenName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        tokenName_ = getDefaultInstance().getTokenName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tokenName = 8;</code>
       */
      public Builder setTokenNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        tokenName_ = value;
        onChanged();
        return this;
      }

      private int transType_ ;
      /**
       * <code>required int32 transType = 9;</code>
       */
      public boolean hasTransType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 transType = 9;</code>
       */
      public int getTransType() {
        return transType_;
      }
      /**
       * <code>required int32 transType = 9;</code>
       */
      public Builder setTransType(int value) {
        bitField0_ |= 0x00000100;
        transType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 transType = 9;</code>
       */
      public Builder clearTransType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        transType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final com.photon.photonchain.network.proto.TransactionMessage.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.photon.photonchain.network.proto.TransactionMessage.Transaction();
    }

    public static com.photon.photonchain.network.proto.TransactionMessage.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    public com.photon.photonchain.network.proto.TransactionMessage.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030TransactionMessage.proto\032\034TransactionH" +
      "eadMessage.proto\"\321\001\n\013Transaction\022\023\n\013bloc" +
      "kHeight\030\001 \002(\003\022\020\n\010lockTime\030\002 \002(\003\022\026\n\016trans" +
      "Signature\030\003 \002(\014\022)\n\017transactionHead\030\004 \002(\013" +
      "2\020.TransactionHead\022\021\n\ttransFrom\030\005 \002(\t\022\017\n" +
      "\007transTo\030\006 \002(\t\022\016\n\006remark\030\007 \001(\t\022\021\n\ttokenN" +
      "ame\030\010 \002(\t\022\021\n\ttransType\030\t \002(\005B:\n$com.phot" +
      "on.photonchain.network.protoB\022Transactio" +
      "nMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.photon.photonchain.network.proto.TransactionHeadMessage.getDescriptor(),
        }, assigner);
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "BlockHeight", "LockTime", "TransSignature", "TransactionHead", "TransFrom", "TransTo", "Remark", "TokenName", "TransType", });
    com.photon.photonchain.network.proto.TransactionHeadMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
