// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionHeadMessage.proto

package com.photon.photonchain.network.proto;

public final class TransactionHeadMessage {
  private TransactionHeadMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransactionHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string transFrom = 1;</code>
     */
    boolean hasTransFrom();
    /**
     * <code>required string transFrom = 1;</code>
     */
    java.lang.String getTransFrom();
    /**
     * <code>required string transFrom = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransFromBytes();

    /**
     * <code>required string transTo = 2;</code>
     */
    boolean hasTransTo();
    /**
     * <code>required string transTo = 2;</code>
     */
    java.lang.String getTransTo();
    /**
     * <code>required string transTo = 2;</code>
     */
    com.google.protobuf.ByteString
        getTransToBytes();

    /**
     * <code>required int64 transValue = 3;</code>
     */
    boolean hasTransValue();
    /**
     * <code>required int64 transValue = 3;</code>
     */
    long getTransValue();

    /**
     * <code>required int64 fee = 4;</code>
     */
    boolean hasFee();
    /**
     * <code>required int64 fee = 4;</code>
     */
    long getFee();

    /**
     * <code>required int64 timeStamp = 5;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required int64 timeStamp = 5;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code TransactionHead}
   */
  public  static final class TransactionHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransactionHead)
      TransactionHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionHead.newBuilder() to construct.
    private TransactionHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionHead() {
      transFrom_ = "";
      transTo_ = "";
      transValue_ = 0L;
      fee_ = 0L;
      timeStamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              transFrom_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              transTo_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              transValue_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              fee_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.photon.photonchain.network.proto.TransactionHeadMessage.internal_static_TransactionHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.photon.photonchain.network.proto.TransactionHeadMessage.internal_static_TransactionHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.class, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder.class);
    }

    private int bitField0_;
    public static final int TRANSFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object transFrom_;
    /**
     * <code>required string transFrom = 1;</code>
     */
    public boolean hasTransFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string transFrom = 1;</code>
     */
    public java.lang.String getTransFrom() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transFrom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransFromBytes() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object transTo_;
    /**
     * <code>required string transTo = 2;</code>
     */
    public boolean hasTransTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string transTo = 2;</code>
     */
    public java.lang.String getTransTo() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transTo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransToBytes() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSVALUE_FIELD_NUMBER = 3;
    private long transValue_;
    /**
     * <code>required int64 transValue = 3;</code>
     */
    public boolean hasTransValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 transValue = 3;</code>
     */
    public long getTransValue() {
      return transValue_;
    }

    public static final int FEE_FIELD_NUMBER = 4;
    private long fee_;
    /**
     * <code>required int64 fee = 4;</code>
     */
    public boolean hasFee() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 fee = 4;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    /**
     * <code>required int64 timeStamp = 5;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 timeStamp = 5;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTransFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, transValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, fee_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timeStamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, transValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fee_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeStamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead)) {
        return super.equals(obj);
      }
      com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead other = (com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead) obj;

      boolean result = true;
      result = result && (hasTransFrom() == other.hasTransFrom());
      if (hasTransFrom()) {
        result = result && getTransFrom()
            .equals(other.getTransFrom());
      }
      result = result && (hasTransTo() == other.hasTransTo());
      if (hasTransTo()) {
        result = result && getTransTo()
            .equals(other.getTransTo());
      }
      result = result && (hasTransValue() == other.hasTransValue());
      if (hasTransValue()) {
        result = result && (getTransValue()
            == other.getTransValue());
      }
      result = result && (hasFee() == other.hasFee());
      if (hasFee()) {
        result = result && (getFee()
            == other.getFee());
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && (getTimeStamp()
            == other.getTimeStamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransFrom()) {
        hash = (37 * hash) + TRANSFROM_FIELD_NUMBER;
        hash = (53 * hash) + getTransFrom().hashCode();
      }
      if (hasTransTo()) {
        hash = (37 * hash) + TRANSTO_FIELD_NUMBER;
        hash = (53 * hash) + getTransTo().hashCode();
      }
      if (hasTransValue()) {
        hash = (37 * hash) + TRANSVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTransValue());
      }
      if (hasFee()) {
        hash = (37 * hash) + FEE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFee());
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransactionHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransactionHead)
        com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.photon.photonchain.network.proto.TransactionHeadMessage.internal_static_TransactionHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.photon.photonchain.network.proto.TransactionHeadMessage.internal_static_TransactionHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.class, com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.Builder.class);
      }

      // Construct using com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        transFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        transTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        transValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        fee_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.photon.photonchain.network.proto.TransactionHeadMessage.internal_static_TransactionHead_descriptor;
      }

      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getDefaultInstanceForType() {
        return com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance();
      }

      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead build() {
        com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead buildPartial() {
        com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead result = new com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transFrom_ = transFrom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.transTo_ = transTo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.transValue_ = transValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fee_ = fee_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeStamp_ = timeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead) {
          return mergeFrom((com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead other) {
        if (other == com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead.getDefaultInstance()) return this;
        if (other.hasTransFrom()) {
          bitField0_ |= 0x00000001;
          transFrom_ = other.transFrom_;
          onChanged();
        }
        if (other.hasTransTo()) {
          bitField0_ |= 0x00000002;
          transTo_ = other.transTo_;
          onChanged();
        }
        if (other.hasTransValue()) {
          setTransValue(other.getTransValue());
        }
        if (other.hasFee()) {
          setFee(other.getFee());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransFrom()) {
          return false;
        }
        if (!hasTransTo()) {
          return false;
        }
        if (!hasTransValue()) {
          return false;
        }
        if (!hasFee()) {
          return false;
        }
        if (!hasTimeStamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object transFrom_ = "";
      /**
       * <code>required string transFrom = 1;</code>
       */
      public boolean hasTransFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public java.lang.String getTransFrom() {
        java.lang.Object ref = transFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransFromBytes() {
        java.lang.Object ref = transFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder setTransFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder clearTransFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transFrom_ = getDefaultInstance().getTransFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder setTransFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transTo_ = "";
      /**
       * <code>required string transTo = 2;</code>
       */
      public boolean hasTransTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public java.lang.String getTransTo() {
        java.lang.Object ref = transTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTransToBytes() {
        java.lang.Object ref = transTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder setTransTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder clearTransTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        transTo_ = getDefaultInstance().getTransTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder setTransToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transTo_ = value;
        onChanged();
        return this;
      }

      private long transValue_ ;
      /**
       * <code>required int64 transValue = 3;</code>
       */
      public boolean hasTransValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 transValue = 3;</code>
       */
      public long getTransValue() {
        return transValue_;
      }
      /**
       * <code>required int64 transValue = 3;</code>
       */
      public Builder setTransValue(long value) {
        bitField0_ |= 0x00000004;
        transValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transValue = 3;</code>
       */
      public Builder clearTransValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        transValue_ = 0L;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>required int64 fee = 4;</code>
       */
      public boolean hasFee() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 fee = 4;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>required int64 fee = 4;</code>
       */
      public Builder setFee(long value) {
        bitField0_ |= 0x00000008;
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fee = 4;</code>
       */
      public Builder clearFee() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fee_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>required int64 timeStamp = 5;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 timeStamp = 5;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required int64 timeStamp = 5;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000010;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransactionHead)
    }

    // @@protoc_insertion_point(class_scope:TransactionHead)
    private static final com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead();
    }

    public static com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransactionHead>
        PARSER = new com.google.protobuf.AbstractParser<TransactionHead>() {
      public TransactionHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionHead> getParserForType() {
      return PARSER;
    }

    public com.photon.photonchain.network.proto.TransactionHeadMessage.TransactionHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034TransactionHeadMessage.proto\"i\n\017Transa" +
      "ctionHead\022\021\n\ttransFrom\030\001 \002(\t\022\017\n\007transTo\030" +
      "\002 \002(\t\022\022\n\ntransValue\030\003 \002(\003\022\013\n\003fee\030\004 \002(\003\022\021" +
      "\n\ttimeStamp\030\005 \002(\003B>\n$com.photon.photonch" +
      "ain.network.protoB\026TransactionHeadMessag" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransactionHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionHead_descriptor,
        new java.lang.String[] { "TransFrom", "TransTo", "TransValue", "Fee", "TimeStamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
