// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnconfirmedTranMessage.proto

package com.photon.photonchain.network.proto;

public final class UnconfirmedTranMessage {
  private UnconfirmedTranMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnconfirmedTranOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnconfirmedTran)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string transFrom = 1;</code>
     */
    boolean hasTransFrom();
    /**
     * <code>required string transFrom = 1;</code>
     */
    java.lang.String getTransFrom();
    /**
     * <code>required string transFrom = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransFromBytes();

    /**
     * <code>required string transTo = 2;</code>
     */
    boolean hasTransTo();
    /**
     * <code>required string transTo = 2;</code>
     */
    java.lang.String getTransTo();
    /**
     * <code>required string transTo = 2;</code>
     */
    com.google.protobuf.ByteString
        getTransToBytes();

    /**
     * <code>required string remark = 3;</code>
     */
    boolean hasRemark();
    /**
     * <code>required string remark = 3;</code>
     */
    java.lang.String getRemark();
    /**
     * <code>required string remark = 3;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>required string tokenName = 4;</code>
     */
    boolean hasTokenName();
    /**
     * <code>required string tokenName = 4;</code>
     */
    java.lang.String getTokenName();
    /**
     * <code>required string tokenName = 4;</code>
     */
    com.google.protobuf.ByteString
        getTokenNameBytes();

    /**
     * <code>required int64 transValue = 5;</code>
     */
    boolean hasTransValue();
    /**
     * <code>required int64 transValue = 5;</code>
     */
    long getTransValue();

    /**
     * <code>required int64 fee = 6;</code>
     */
    boolean hasFee();
    /**
     * <code>required int64 fee = 6;</code>
     */
    long getFee();

    /**
     * <code>required int64 timeStamp = 7;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required int64 timeStamp = 7;</code>
     */
    long getTimeStamp();

    /**
     * <code>required int32 transType = 8;</code>
     */
    boolean hasTransType();
    /**
     * <code>required int32 transType = 8;</code>
     */
    int getTransType();

    /**
     * <code>required bytes transSignature = 9;</code>
     */
    boolean hasTransSignature();
    /**
     * <code>required bytes transSignature = 9;</code>
     */
    com.google.protobuf.ByteString getTransSignature();

    /**
     * <code>required string contractBin = 10;</code>
     */
    boolean hasContractBin();
    /**
     * <code>required string contractBin = 10;</code>
     */
    java.lang.String getContractBin();
    /**
     * <code>required string contractBin = 10;</code>
     */
    com.google.protobuf.ByteString
        getContractBinBytes();

    /**
     * <code>required string contractAddress = 11;</code>
     */
    boolean hasContractAddress();
    /**
     * <code>required string contractAddress = 11;</code>
     */
    java.lang.String getContractAddress();
    /**
     * <code>required string contractAddress = 11;</code>
     */
    com.google.protobuf.ByteString
        getContractAddressBytes();

    /**
     * <code>required int32 contractType = 12;</code>
     */
    boolean hasContractType();
    /**
     * <code>required int32 contractType = 12;</code>
     */
    int getContractType();

    /**
     * <code>required int32 contractState = 13;</code>
     */
    boolean hasContractState();
    /**
     * <code>required int32 contractState = 13;</code>
     */
    int getContractState();

    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    boolean hasUniqueAddress();
    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    java.lang.String getUniqueAddress();
    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    com.google.protobuf.ByteString
        getUniqueAddressBytes();

    /**
     * <code>required string exchengeToken = 15;</code>
     */
    boolean hasExchengeToken();
    /**
     * <code>required string exchengeToken = 15;</code>
     */
    java.lang.String getExchengeToken();
    /**
     * <code>required string exchengeToken = 15;</code>
     */
    com.google.protobuf.ByteString
        getExchengeTokenBytes();
  }
  /**
   * Protobuf type {@code UnconfirmedTran}
   */
  public  static final class UnconfirmedTran extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UnconfirmedTran)
      UnconfirmedTranOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnconfirmedTran.newBuilder() to construct.
    private UnconfirmedTran(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnconfirmedTran() {
      transFrom_ = "";
      transTo_ = "";
      remark_ = "";
      tokenName_ = "";
      transValue_ = 0L;
      fee_ = 0L;
      timeStamp_ = 0L;
      transType_ = 0;
      transSignature_ = com.google.protobuf.ByteString.EMPTY;
      contractBin_ = "";
      contractAddress_ = "";
      contractType_ = 0;
      contractState_ = 0;
      uniqueAddress_ = "";
      exchengeToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnconfirmedTran(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              transFrom_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              transTo_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              remark_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              tokenName_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              transValue_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              fee_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              timeStamp_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              transType_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              transSignature_ = input.readBytes();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              contractBin_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              contractAddress_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              contractType_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              contractState_ = input.readInt32();
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              uniqueAddress_ = bs;
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00004000;
              exchengeToken_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.photon.photonchain.network.proto.UnconfirmedTranMessage.internal_static_UnconfirmedTran_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.photon.photonchain.network.proto.UnconfirmedTranMessage.internal_static_UnconfirmedTran_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.class, com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.Builder.class);
    }

    private int bitField0_;
    public static final int TRANSFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object transFrom_;
    /**
     * <code>required string transFrom = 1;</code>
     */
    public boolean hasTransFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string transFrom = 1;</code>
     */
    public java.lang.String getTransFrom() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transFrom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransFromBytes() {
      java.lang.Object ref = transFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object transTo_;
    /**
     * <code>required string transTo = 2;</code>
     */
    public boolean hasTransTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string transTo = 2;</code>
     */
    public java.lang.String getTransTo() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transTo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransToBytes() {
      java.lang.Object ref = transTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 3;
    private volatile java.lang.Object remark_;
    /**
     * <code>required string remark = 3;</code>
     */
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string remark = 3;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remark_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string remark = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object tokenName_;
    /**
     * <code>required string tokenName = 4;</code>
     */
    public boolean hasTokenName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string tokenName = 4;</code>
     */
    public java.lang.String getTokenName() {
      java.lang.Object ref = tokenName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tokenName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTokenNameBytes() {
      java.lang.Object ref = tokenName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSVALUE_FIELD_NUMBER = 5;
    private long transValue_;
    /**
     * <code>required int64 transValue = 5;</code>
     */
    public boolean hasTransValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 transValue = 5;</code>
     */
    public long getTransValue() {
      return transValue_;
    }

    public static final int FEE_FIELD_NUMBER = 6;
    private long fee_;
    /**
     * <code>required int64 fee = 6;</code>
     */
    public boolean hasFee() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 fee = 6;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timeStamp_;
    /**
     * <code>required int64 timeStamp = 7;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 timeStamp = 7;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int TRANSTYPE_FIELD_NUMBER = 8;
    private int transType_;
    /**
     * <code>required int32 transType = 8;</code>
     */
    public boolean hasTransType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 transType = 8;</code>
     */
    public int getTransType() {
      return transType_;
    }

    public static final int TRANSSIGNATURE_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString transSignature_;
    /**
     * <code>required bytes transSignature = 9;</code>
     */
    public boolean hasTransSignature() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required bytes transSignature = 9;</code>
     */
    public com.google.protobuf.ByteString getTransSignature() {
      return transSignature_;
    }

    public static final int CONTRACTBIN_FIELD_NUMBER = 10;
    private volatile java.lang.Object contractBin_;
    /**
     * <code>required string contractBin = 10;</code>
     */
    public boolean hasContractBin() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string contractBin = 10;</code>
     */
    public java.lang.String getContractBin() {
      java.lang.Object ref = contractBin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contractBin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string contractBin = 10;</code>
     */
    public com.google.protobuf.ByteString
        getContractBinBytes() {
      java.lang.Object ref = contractBin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractBin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTADDRESS_FIELD_NUMBER = 11;
    private volatile java.lang.Object contractAddress_;
    /**
     * <code>required string contractAddress = 11;</code>
     */
    public boolean hasContractAddress() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string contractAddress = 11;</code>
     */
    public java.lang.String getContractAddress() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contractAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string contractAddress = 11;</code>
     */
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTTYPE_FIELD_NUMBER = 12;
    private int contractType_;
    /**
     * <code>required int32 contractType = 12;</code>
     */
    public boolean hasContractType() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 contractType = 12;</code>
     */
    public int getContractType() {
      return contractType_;
    }

    public static final int CONTRACTSTATE_FIELD_NUMBER = 13;
    private int contractState_;
    /**
     * <code>required int32 contractState = 13;</code>
     */
    public boolean hasContractState() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 contractState = 13;</code>
     */
    public int getContractState() {
      return contractState_;
    }

    public static final int UNIQUEADDRESS_FIELD_NUMBER = 14;
    private volatile java.lang.Object uniqueAddress_;
    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    public boolean hasUniqueAddress() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    public java.lang.String getUniqueAddress() {
      java.lang.Object ref = uniqueAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueAddress = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUniqueAddressBytes() {
      java.lang.Object ref = uniqueAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHENGETOKEN_FIELD_NUMBER = 15;
    private volatile java.lang.Object exchengeToken_;
    /**
     * <code>required string exchengeToken = 15;</code>
     */
    public boolean hasExchengeToken() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required string exchengeToken = 15;</code>
     */
    public java.lang.String getExchengeToken() {
      java.lang.Object ref = exchengeToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exchengeToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string exchengeToken = 15;</code>
     */
    public com.google.protobuf.ByteString
        getExchengeTokenBytes() {
      java.lang.Object ref = exchengeToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchengeToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTransFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemark()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTokenName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractBin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUniqueAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExchengeToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, remark_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tokenName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, transValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, fee_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, timeStamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, transType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, transSignature_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, contractBin_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, contractAddress_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, contractType_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, contractState_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, uniqueAddress_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, exchengeToken_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, remark_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tokenName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, transValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, fee_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timeStamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, transType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, transSignature_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, contractBin_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, contractAddress_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, contractType_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, contractState_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, uniqueAddress_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, exchengeToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran)) {
        return super.equals(obj);
      }
      com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran other = (com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran) obj;

      boolean result = true;
      result = result && (hasTransFrom() == other.hasTransFrom());
      if (hasTransFrom()) {
        result = result && getTransFrom()
            .equals(other.getTransFrom());
      }
      result = result && (hasTransTo() == other.hasTransTo());
      if (hasTransTo()) {
        result = result && getTransTo()
            .equals(other.getTransTo());
      }
      result = result && (hasRemark() == other.hasRemark());
      if (hasRemark()) {
        result = result && getRemark()
            .equals(other.getRemark());
      }
      result = result && (hasTokenName() == other.hasTokenName());
      if (hasTokenName()) {
        result = result && getTokenName()
            .equals(other.getTokenName());
      }
      result = result && (hasTransValue() == other.hasTransValue());
      if (hasTransValue()) {
        result = result && (getTransValue()
            == other.getTransValue());
      }
      result = result && (hasFee() == other.hasFee());
      if (hasFee()) {
        result = result && (getFee()
            == other.getFee());
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && (getTimeStamp()
            == other.getTimeStamp());
      }
      result = result && (hasTransType() == other.hasTransType());
      if (hasTransType()) {
        result = result && (getTransType()
            == other.getTransType());
      }
      result = result && (hasTransSignature() == other.hasTransSignature());
      if (hasTransSignature()) {
        result = result && getTransSignature()
            .equals(other.getTransSignature());
      }
      result = result && (hasContractBin() == other.hasContractBin());
      if (hasContractBin()) {
        result = result && getContractBin()
            .equals(other.getContractBin());
      }
      result = result && (hasContractAddress() == other.hasContractAddress());
      if (hasContractAddress()) {
        result = result && getContractAddress()
            .equals(other.getContractAddress());
      }
      result = result && (hasContractType() == other.hasContractType());
      if (hasContractType()) {
        result = result && (getContractType()
            == other.getContractType());
      }
      result = result && (hasContractState() == other.hasContractState());
      if (hasContractState()) {
        result = result && (getContractState()
            == other.getContractState());
      }
      result = result && (hasUniqueAddress() == other.hasUniqueAddress());
      if (hasUniqueAddress()) {
        result = result && getUniqueAddress()
            .equals(other.getUniqueAddress());
      }
      result = result && (hasExchengeToken() == other.hasExchengeToken());
      if (hasExchengeToken()) {
        result = result && getExchengeToken()
            .equals(other.getExchengeToken());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransFrom()) {
        hash = (37 * hash) + TRANSFROM_FIELD_NUMBER;
        hash = (53 * hash) + getTransFrom().hashCode();
      }
      if (hasTransTo()) {
        hash = (37 * hash) + TRANSTO_FIELD_NUMBER;
        hash = (53 * hash) + getTransTo().hashCode();
      }
      if (hasRemark()) {
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemark().hashCode();
      }
      if (hasTokenName()) {
        hash = (37 * hash) + TOKENNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTokenName().hashCode();
      }
      if (hasTransValue()) {
        hash = (37 * hash) + TRANSVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTransValue());
      }
      if (hasFee()) {
        hash = (37 * hash) + FEE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFee());
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStamp());
      }
      if (hasTransType()) {
        hash = (37 * hash) + TRANSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTransType();
      }
      if (hasTransSignature()) {
        hash = (37 * hash) + TRANSSIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getTransSignature().hashCode();
      }
      if (hasContractBin()) {
        hash = (37 * hash) + CONTRACTBIN_FIELD_NUMBER;
        hash = (53 * hash) + getContractBin().hashCode();
      }
      if (hasContractAddress()) {
        hash = (37 * hash) + CONTRACTADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getContractAddress().hashCode();
      }
      if (hasContractType()) {
        hash = (37 * hash) + CONTRACTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContractType();
      }
      if (hasContractState()) {
        hash = (37 * hash) + CONTRACTSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getContractState();
      }
      if (hasUniqueAddress()) {
        hash = (37 * hash) + UNIQUEADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getUniqueAddress().hashCode();
      }
      if (hasExchengeToken()) {
        hash = (37 * hash) + EXCHENGETOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getExchengeToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnconfirmedTran}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnconfirmedTran)
        com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTranOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.photon.photonchain.network.proto.UnconfirmedTranMessage.internal_static_UnconfirmedTran_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.photon.photonchain.network.proto.UnconfirmedTranMessage.internal_static_UnconfirmedTran_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.class, com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.Builder.class);
      }

      // Construct using com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        transFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        transTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tokenName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        transValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        fee_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        transType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        transSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        contractBin_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        contractAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        contractType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        contractState_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        uniqueAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        exchengeToken_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.photon.photonchain.network.proto.UnconfirmedTranMessage.internal_static_UnconfirmedTran_descriptor;
      }

      public com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran getDefaultInstanceForType() {
        return com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.getDefaultInstance();
      }

      public com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran build() {
        com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran buildPartial() {
        com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran result = new com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transFrom_ = transFrom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.transTo_ = transTo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.remark_ = remark_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tokenName_ = tokenName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.transValue_ = transValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.fee_ = fee_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.transType_ = transType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.transSignature_ = transSignature_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.contractBin_ = contractBin_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.contractAddress_ = contractAddress_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.contractType_ = contractType_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.contractState_ = contractState_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.uniqueAddress_ = uniqueAddress_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.exchengeToken_ = exchengeToken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran) {
          return mergeFrom((com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran other) {
        if (other == com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran.getDefaultInstance()) return this;
        if (other.hasTransFrom()) {
          bitField0_ |= 0x00000001;
          transFrom_ = other.transFrom_;
          onChanged();
        }
        if (other.hasTransTo()) {
          bitField0_ |= 0x00000002;
          transTo_ = other.transTo_;
          onChanged();
        }
        if (other.hasRemark()) {
          bitField0_ |= 0x00000004;
          remark_ = other.remark_;
          onChanged();
        }
        if (other.hasTokenName()) {
          bitField0_ |= 0x00000008;
          tokenName_ = other.tokenName_;
          onChanged();
        }
        if (other.hasTransValue()) {
          setTransValue(other.getTransValue());
        }
        if (other.hasFee()) {
          setFee(other.getFee());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasTransType()) {
          setTransType(other.getTransType());
        }
        if (other.hasTransSignature()) {
          setTransSignature(other.getTransSignature());
        }
        if (other.hasContractBin()) {
          bitField0_ |= 0x00000200;
          contractBin_ = other.contractBin_;
          onChanged();
        }
        if (other.hasContractAddress()) {
          bitField0_ |= 0x00000400;
          contractAddress_ = other.contractAddress_;
          onChanged();
        }
        if (other.hasContractType()) {
          setContractType(other.getContractType());
        }
        if (other.hasContractState()) {
          setContractState(other.getContractState());
        }
        if (other.hasUniqueAddress()) {
          bitField0_ |= 0x00002000;
          uniqueAddress_ = other.uniqueAddress_;
          onChanged();
        }
        if (other.hasExchengeToken()) {
          bitField0_ |= 0x00004000;
          exchengeToken_ = other.exchengeToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransFrom()) {
          return false;
        }
        if (!hasTransTo()) {
          return false;
        }
        if (!hasRemark()) {
          return false;
        }
        if (!hasTokenName()) {
          return false;
        }
        if (!hasTransValue()) {
          return false;
        }
        if (!hasFee()) {
          return false;
        }
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasTransType()) {
          return false;
        }
        if (!hasTransSignature()) {
          return false;
        }
        if (!hasContractBin()) {
          return false;
        }
        if (!hasContractAddress()) {
          return false;
        }
        if (!hasContractType()) {
          return false;
        }
        if (!hasContractState()) {
          return false;
        }
        if (!hasUniqueAddress()) {
          return false;
        }
        if (!hasExchengeToken()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object transFrom_ = "";
      /**
       * <code>required string transFrom = 1;</code>
       */
      public boolean hasTransFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public java.lang.String getTransFrom() {
        java.lang.Object ref = transFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransFromBytes() {
        java.lang.Object ref = transFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder setTransFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder clearTransFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transFrom_ = getDefaultInstance().getTransFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string transFrom = 1;</code>
       */
      public Builder setTransFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transTo_ = "";
      /**
       * <code>required string transTo = 2;</code>
       */
      public boolean hasTransTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public java.lang.String getTransTo() {
        java.lang.Object ref = transTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTransToBytes() {
        java.lang.Object ref = transTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder setTransTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder clearTransTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        transTo_ = getDefaultInstance().getTransTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string transTo = 2;</code>
       */
      public Builder setTransToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>required string remark = 3;</code>
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string remark = 3;</code>
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remark_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string remark = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string remark = 3;</code>
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string remark = 3;</code>
       */
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00000004);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>required string remark = 3;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remark_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenName_ = "";
      /**
       * <code>required string tokenName = 4;</code>
       */
      public boolean hasTokenName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string tokenName = 4;</code>
       */
      public java.lang.String getTokenName() {
        java.lang.Object ref = tokenName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tokenName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tokenName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTokenNameBytes() {
        java.lang.Object ref = tokenName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tokenName = 4;</code>
       */
      public Builder setTokenName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tokenName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tokenName = 4;</code>
       */
      public Builder clearTokenName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tokenName_ = getDefaultInstance().getTokenName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tokenName = 4;</code>
       */
      public Builder setTokenNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tokenName_ = value;
        onChanged();
        return this;
      }

      private long transValue_ ;
      /**
       * <code>required int64 transValue = 5;</code>
       */
      public boolean hasTransValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 transValue = 5;</code>
       */
      public long getTransValue() {
        return transValue_;
      }
      /**
       * <code>required int64 transValue = 5;</code>
       */
      public Builder setTransValue(long value) {
        bitField0_ |= 0x00000010;
        transValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transValue = 5;</code>
       */
      public Builder clearTransValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        transValue_ = 0L;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>required int64 fee = 6;</code>
       */
      public boolean hasFee() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 fee = 6;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>required int64 fee = 6;</code>
       */
      public Builder setFee(long value) {
        bitField0_ |= 0x00000020;
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fee = 6;</code>
       */
      public Builder clearFee() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fee_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>required int64 timeStamp = 7;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 timeStamp = 7;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required int64 timeStamp = 7;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000040;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStamp = 7;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private int transType_ ;
      /**
       * <code>required int32 transType = 8;</code>
       */
      public boolean hasTransType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 transType = 8;</code>
       */
      public int getTransType() {
        return transType_;
      }
      /**
       * <code>required int32 transType = 8;</code>
       */
      public Builder setTransType(int value) {
        bitField0_ |= 0x00000080;
        transType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 transType = 8;</code>
       */
      public Builder clearTransType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        transType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes transSignature = 9;</code>
       */
      public boolean hasTransSignature() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required bytes transSignature = 9;</code>
       */
      public com.google.protobuf.ByteString getTransSignature() {
        return transSignature_;
      }
      /**
       * <code>required bytes transSignature = 9;</code>
       */
      public Builder setTransSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        transSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes transSignature = 9;</code>
       */
      public Builder clearTransSignature() {
        bitField0_ = (bitField0_ & ~0x00000100);
        transSignature_ = getDefaultInstance().getTransSignature();
        onChanged();
        return this;
      }

      private java.lang.Object contractBin_ = "";
      /**
       * <code>required string contractBin = 10;</code>
       */
      public boolean hasContractBin() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string contractBin = 10;</code>
       */
      public java.lang.String getContractBin() {
        java.lang.Object ref = contractBin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contractBin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string contractBin = 10;</code>
       */
      public com.google.protobuf.ByteString
          getContractBinBytes() {
        java.lang.Object ref = contractBin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractBin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string contractBin = 10;</code>
       */
      public Builder setContractBin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        contractBin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string contractBin = 10;</code>
       */
      public Builder clearContractBin() {
        bitField0_ = (bitField0_ & ~0x00000200);
        contractBin_ = getDefaultInstance().getContractBin();
        onChanged();
        return this;
      }
      /**
       * <code>required string contractBin = 10;</code>
       */
      public Builder setContractBinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        contractBin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contractAddress_ = "";
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public boolean hasContractAddress() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public java.lang.String getContractAddress() {
        java.lang.Object ref = contractAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contractAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public com.google.protobuf.ByteString
          getContractAddressBytes() {
        java.lang.Object ref = contractAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public Builder setContractAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        contractAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public Builder clearContractAddress() {
        bitField0_ = (bitField0_ & ~0x00000400);
        contractAddress_ = getDefaultInstance().getContractAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string contractAddress = 11;</code>
       */
      public Builder setContractAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        contractAddress_ = value;
        onChanged();
        return this;
      }

      private int contractType_ ;
      /**
       * <code>required int32 contractType = 12;</code>
       */
      public boolean hasContractType() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 contractType = 12;</code>
       */
      public int getContractType() {
        return contractType_;
      }
      /**
       * <code>required int32 contractType = 12;</code>
       */
      public Builder setContractType(int value) {
        bitField0_ |= 0x00000800;
        contractType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contractType = 12;</code>
       */
      public Builder clearContractType() {
        bitField0_ = (bitField0_ & ~0x00000800);
        contractType_ = 0;
        onChanged();
        return this;
      }

      private int contractState_ ;
      /**
       * <code>required int32 contractState = 13;</code>
       */
      public boolean hasContractState() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int32 contractState = 13;</code>
       */
      public int getContractState() {
        return contractState_;
      }
      /**
       * <code>required int32 contractState = 13;</code>
       */
      public Builder setContractState(int value) {
        bitField0_ |= 0x00001000;
        contractState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contractState = 13;</code>
       */
      public Builder clearContractState() {
        bitField0_ = (bitField0_ & ~0x00001000);
        contractState_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uniqueAddress_ = "";
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public boolean hasUniqueAddress() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public java.lang.String getUniqueAddress() {
        java.lang.Object ref = uniqueAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uniqueAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public com.google.protobuf.ByteString
          getUniqueAddressBytes() {
        java.lang.Object ref = uniqueAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public Builder setUniqueAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        uniqueAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public Builder clearUniqueAddress() {
        bitField0_ = (bitField0_ & ~0x00002000);
        uniqueAddress_ = getDefaultInstance().getUniqueAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueAddress = 14;</code>
       */
      public Builder setUniqueAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        uniqueAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchengeToken_ = "";
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public boolean hasExchengeToken() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public java.lang.String getExchengeToken() {
        java.lang.Object ref = exchengeToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchengeToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public com.google.protobuf.ByteString
          getExchengeTokenBytes() {
        java.lang.Object ref = exchengeToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchengeToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public Builder setExchengeToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        exchengeToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public Builder clearExchengeToken() {
        bitField0_ = (bitField0_ & ~0x00004000);
        exchengeToken_ = getDefaultInstance().getExchengeToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string exchengeToken = 15;</code>
       */
      public Builder setExchengeTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        exchengeToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UnconfirmedTran)
    }

    // @@protoc_insertion_point(class_scope:UnconfirmedTran)
    private static final com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran();
    }

    public static com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UnconfirmedTran>
        PARSER = new com.google.protobuf.AbstractParser<UnconfirmedTran>() {
      public UnconfirmedTran parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnconfirmedTran(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnconfirmedTran> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnconfirmedTran> getParserForType() {
      return PARSER;
    }

    public com.photon.photonchain.network.proto.UnconfirmedTranMessage.UnconfirmedTran getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnconfirmedTran_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnconfirmedTran_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034UnconfirmedTranMessage.proto\"\300\002\n\017Uncon" +
      "firmedTran\022\021\n\ttransFrom\030\001 \002(\t\022\017\n\007transTo" +
      "\030\002 \002(\t\022\016\n\006remark\030\003 \002(\t\022\021\n\ttokenName\030\004 \002(" +
      "\t\022\022\n\ntransValue\030\005 \002(\003\022\013\n\003fee\030\006 \002(\003\022\021\n\tti" +
      "meStamp\030\007 \002(\003\022\021\n\ttransType\030\010 \002(\005\022\026\n\016tran" +
      "sSignature\030\t \002(\014\022\023\n\013contractBin\030\n \002(\t\022\027\n" +
      "\017contractAddress\030\013 \002(\t\022\024\n\014contractType\030\014" +
      " \002(\005\022\025\n\rcontractState\030\r \002(\005\022\025\n\runiqueAdd" +
      "ress\030\016 \002(\t\022\025\n\rexchengeToken\030\017 \002(\tB>\n$com" +
      ".photon.photonchain.network.protoB\026Uncon" +
      "firmedTranMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UnconfirmedTran_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UnconfirmedTran_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnconfirmedTran_descriptor,
        new java.lang.String[] { "TransFrom", "TransTo", "Remark", "TokenName", "TransValue", "Fee", "TimeStamp", "TransType", "TransSignature", "ContractBin", "ContractAddress", "ContractType", "ContractState", "UniqueAddress", "ExchengeToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
